import datasetJson from "../../../data/korean-foods.json";
import { foodDatasetSchema, parseFoodEntries } from "./dataset";
import { createLocalDatasetResolver } from "./localDatasetResolver";
import { withServingReferences } from "./servingReferences";
import type { FoodEntry, NutritionResolver } from "./types";

/**
 * The bundled Korean food dataset, wired to a resolver.
 *
 * The file is generated by `pnpm sync:mfds` from the 식약처 food-nutrition
 * open API and committed, so the app has no network dependency at request
 * time and the test suite stays offline. Every figure in it carries the MFDS
 * food code it came from in its `source` field.
 *
 * Validation runs at import: the envelope is checked, and individual rows go
 * through `parseFoodEntries`, which drops a malformed entry rather than
 * letting one bad row blank the whole dataset.
 */

const parsed = foodDatasetSchema.safeParse(datasetJson);

if (!parsed.success) {
  throw new Error(
    `data/korean-foods.json does not match the dataset schema. Re-run \`pnpm sync:mfds\`.`,
  );
}

/** Where the figures came from, for attribution in the UI and the README. */
export const DATASET_SOURCE = parsed.data.source;

/**
 * Exactly what MFDS published, as the sync wrote it. Kept separate so the
 * seed invariants can be checked against the rows themselves.
 */
export const MFDS_FOOD_ENTRIES: FoodEntry[] = parseFoodEntries(parsed.data.entries);

/**
 * What the app resolves against: the MFDS entries plus the published
 * household measures in `servingReferences.ts` — "계란 1개 = 50 g" — which
 * MFDS itself does not carry. The references add grams per unit only; every
 * calorie figure is still the row's.
 */
export const KOREAN_FOODS: FoodEntry[] = withServingReferences(MFDS_FOOD_ENTRIES);

/**
 * How many foods the app can actually price. Deliberately exported: the gap
 * between this and what people really eat is the honest limit of the MVP,
 * and anything outside it resolves to `unknown` rather than to a guess.
 */
export const KOREAN_FOOD_COUNT = KOREAN_FOODS.length;

export const koreanFoodResolver: NutritionResolver =
  createLocalDatasetResolver(KOREAN_FOODS);
